version: '3.4'

services:
    db:
        image: postgres
        container_name: db
        restart: always
        ports:
            - '${DB_PORT}:5432'
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    db-test:
        image: postgres
        container_name: db-test
        restart: always
        ports:
            - '${DB_TEST_PORT}:5432'
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
